version: "3"
services:
  auth-service:
    restart: unless-stopped
    build: "."
    working_dir: "/var/www/auth-server/"
    command: "npm run server"
    tty: true
    ports:
      - "443:443"
    volumes:
      - ".:/var/www/auth-server"
networks:
  default:
    external:
      name: api_network
